### ISSUE TITLE
高并发情况图片会上传失败

### ISSUE THREAD

**Issue by lsisconl** [KonataDev/Konata.Core#128]
**Environment / 环境**
1.0.9

**Stack trace / 堆栈信息**
A task was canceled.
   at Konata.Core.Components.InternalComponent.SendPacket[TEvent](ProtocolEvent anyEvent, Int32 timeout)
   at Konata.Core.Logics.Model.MessagingLogic.UploadImages(List`1 image, Boolean c2c, UInt32 uin)
   at Konata.Core.Logics.Model.MessagingLogic.SearchImageAndUpload(UInt32 uin, MessageChain message, Boolean c2c)
   at Konata.Core.Logics.Model.MessagingLogic.SendGroupMessage(UInt32 groupUin, MessageChain message)
   at Maikon.Events.Group.OnGroupMessage(Object sender, GroupMessageEvent groupMessageEvent) in E:\Maikon\Events\Group.cs:line 51

**Comment by lsisconl** [comment]
在版本1.2.0a1中，此问题得到解决 @TheSnowfield

**Comment by TheSnowfield** [comment]
> 在版本1.2.0a1中，此问题得到解决 @TheSnowfield

一觉醒来, bug自己好了
