### ISSUE TITLE
[bug report] Socket crash when reconnect

### ISSUE THREAD

**Issue by TheSnowfield** [KonataDev/Konata.Core#137]
```
Unhandled exception. System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Kernel32.SetFileCompletionNotificationModes(SafeHandle handle, FileCompletionNotificationModes flags)
   at System.Net.Sockets.SafeSocketHandle.GetOrAllocateThreadPoolBoundHandle(Boolean trySkipCompletionPortOnSuccess)
   at System.Net.Sockets.Socket.GetOrAllocateThreadPoolBoundHandleSlow()
   at System.Net.Sockets.SocketAsyncEventArgs.DoOperationConnectEx(Socket socket, SafeSocketHandle handle)
   at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e, Boolean userSocket, Boolean saeaCancelable)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ConnectAsync(String host, Int32 port)
   at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at Konata.Core.Utils.TcpSocket.FeaturedSocket.TryConnect(String host, Int32 port, AsyncCallback requestCallback, Object state) in M:\Projects\KonataDev\Konata.Stdout\Konata.Core\Konata.Core\Utils\TcpSocket\AsyncClient.cs:line 252
   at Konata.Core.Utils.TcpSocket.AsyncClient.Reconnect() in M:\Projects\KonataDev\Konata.Stdout\Konata.Core\Konata.Core\Utils\TcpSocket\AsyncClient.cs:line 95
   at Konata.Core.Components.Logics.Model.WtExchangeLogic.OnCheckConnection() in M:\Projects\KonataDev\Konata.Stdout\Konata.Core\Konata.Core\Components\Logics\Model\WtExchangeLogic.cs:line 358
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by TheSnowfield** [comment]
#137
