### ISSUE TITLE
[bug report] silk codec crashed

### ISSUE THREAD

**Issue by TheSnowfield** [KonataDev/Konata.Core#149]
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Konata.Codec.Audio.Codecs.SilkV3Codec.SilkEncode(IntPtr, Int32, Int32, CodecCallback, IntPtr)
--------------------------------
   at Konata.Codec.Audio.Codecs.SilkV3Codec+Encoder.Read(Byte[], Int32, Int32)
   at System.IO.Stream.CopyTo(System.IO.Stream, Int32)
   at System.IO.MemoryStream.CopyTo(System.IO.Stream, Int32)
   at System.IO.Stream.CopyTo(System.IO.Stream)
   at Konata.Codec.Audio.AudioPipeline.<Start>b__2_0()
   at System.Threading.Tasks.Task`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

**Comment by TheSnowfield** [comment]
![4_2D)OP%ZZEE~ (RR1UH8MD](https://user-images.githubusercontent.com/17957399/162482274-b6e5d638-fd53-4979-93ef-32101b66204c.png)
native codec issue, transferred.
